[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "leleka"
version = "0.1.0"
description = "The Stork is watching... Lightweight LLM CLI Tool"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Flo" }]

dependencies = [
    "typer>=0.12.0",
    "rich>=13.0.0",
    "ollama>=0.3.0",
]

[project.scripts]
leleka = "leleka.main:app"

[tool.setuptools.packages.find]
where = ["src"]
